import Head from "next/head";
import { Footer } from "../components/Footer";
import { Main } from "../components/Main";
import { Header } from "../components/Header";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Abount Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />
      <Main page="about" />
      <Footer />
    </div>
  );
}
