import Head from "next/head";
import { Footer } from "../components/Footer";
import { Main } from "../components/Main";
import { Header } from "../components/Header";
import styles from "./styles/Home.module.css";
import { useCallback, useEffect, useState } from "react";


export default function Home() {
  const [count, setCount] = useState(1);
  const [ text, setText ] = useState("");
  const [ isShow, setIsShow ] = useState(true);
  const [ array, setArray ] = useState([]);

  const handleClick = useCallback(() => {
    if(count < 10){
      setCount((prevCount) => prevCount + 1);
    }
  }, [count]);

  const handleDisplay = useCallback(() => {
    setIsShow((prevIsShow) => !prevIsShow);
  }, []);

  useEffect(() => {
    document.body.style.backgroundColor = "lightblue";
    return () => {
      document.body.style.backgroundColor = "";
    }
  }, []);

  const handleChange = useCallback((e) => {
    if(e.target.value.length > 5) {
      alert("max 5");
      return;
    }
    setText(e.target.value.trim());
  }, []);

  const handleAdd = useCallback(() => {
    setArray((prevArray) => {
      if (prevArray.some(item => item === text)){
        alert("同じ要素がすでに存在します。")
      }
      return [...prevArray, text];
    })
  }, [text]);
  return (
    <div className={styles.container}>
      <Head>
        <title>Index Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />
      {isShow ? <h1>{ count }</h1> : null}
      <button onClick={handleClick}>ボタン</button>
      <button onClick={handleDisplay}>{isShow ? "非表示" : "表示"}</button>
      <input type="text" value={text} onChange={handleChange} />
      <button onClick={handleAdd}>追加</button>
      <ul>
        {array.map(item => {
          return (
            <li key={item}>{item}</li>
          )
        })}
      </ul>
      <Main page="index" />
      <Footer/>
    </div>
  );
}
