import Head from "next/head";
import { Footer } from "../components/Footer";
import { Main } from "../components/Main";
import { Header } from "../components/Header";
import styles from "./styles/Home.module.css";
import { useCallback, useEffect } from "react";

const handleClick = (e) => {
  e.preventDefault();
  alert(123)
};

export default function Home() {
  useEffect(() => {
    document.body.style.backgroundColor = "lightblue";

    return () => {
      document.body.style.backgroundColor = "";
    }
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Index Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />
      <button
        onClick={handleClick}
      >
        ボタン
      </button>
      <Main page="index" />
      <Footer/>
    </div>
  );
}
